// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * OpenFile 讀取指定路徑的檔案內容與編碼
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileResult | null>}
 */
export function OpenFile(path) {
    return $Call.ByID(1958968983, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveFile 將內容與指定的編碼格式寫入指定路徑的檔案中
 * @param {string} path
 * @param {string} content
 * @param {string} encoding
 * @returns {$CancellablePromise<void>}
 */
export function SaveFile(path, content, encoding) {
    return $Call.ByID(1396636678, path, content, encoding);
}

/**
 * SelectFile 喚起系統原生開啟檔案對話框，返回選擇的檔案路徑
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(2427571203);
}

/**
 * SelectSaveFile 喚起系統原生儲存檔案對話框，返回選擇的儲存路徑
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function SelectSaveFile(defaultName) {
    return $Call.ByID(893202942, defaultName);
}

// Private type creation functions
const $$createType0 = $models.FileResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
