// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileResult 包含檔案內容與偵測到的編碼名稱
 */
export class FileResult {
    /**
     * Creates a new FileResult instance.
     * @param {Partial<FileResult>} [$$source = {}] - The source object to create the FileResult.
     */
    constructor($$source = {}) {
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("encoding" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["encoding"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileResult(/** @type {Partial<FileResult>} */($$parsedSource));
    }
}
